### PR TITLE
Support Activity Anchoring + Refactoring/Improvements

### LINKED ISSUE #1: Support Relative Activity Timing
This was actually added in Aerie 1.1.0, but I'm tagging it for a v1.2.0 milestone release.

Notes from the original issue:
> activity directives have definitely changed (two new fields: `anchor_id` and `anchored_to_start`). Simulated activity instances should be the same as before - nothing downstream of simulation should have changed.

- [x] Update dataclasses
- [x] Build in backwards-compatibility
- [x] Test all affected plan interfaces + build test cases (create activity, update activity, upload plan, download plan)
- [x] Document breaking changes

### LINKED ISSUE #2: Revisit string parsing
Postgres intervals are used in the start offset of resource profile segments and the parsing of those strings could be improved.

### PR DESCRIPTION
**Pull request by cartermak**
Support activity anchoring by adding necessary fields on `Activity` data structures. The implications of this are that the previous logic to evaluate absolute start times is flawed and would couple values on `Activity` objects. 

Additionally, the addition of anchoring poses an issue for uploading plans because referenced anchor IDs need to be updated. A summary of this is captured [here](https://github.com/NASA-AMMOS/aerie/issues/836). 

Because of the scope of the necessary changes, I took this as an opportunity to refactor the activity dataclasses and remove the notion of a client-side "Create" class for activities.

Breaking changes:

- `ActivityRead` and `ActivityCreate` are now consolidated to `Activity`.
- The `Activity` field `parameters` has been deprecated in favor of `arguments`, which reflects the naming used in Aerie.
- Activities no longer are stored with a calculated absolute `start_time` field; instead, activities have a `start_offset` and fields `anchor_id` and `anchored_to_start` which reflect how activity timing is defined in Aerie. Evaluate the effective start time of an activity within a plan using `ActivityPlanRead.get_activity_start_time()`.
- The `AerieClient.create_activity()` and `Activity.to_api_create()` methods no longer require plan start time to be passed as a parameter.

Closes #1 
Closes #2

### CODE REVIEW

**Comment by martyvona** [comment]
@cartermak this has been open for a while, is there a reason?

**Comment by cartermak** [comment]
@martyvona Only because I still need someone to review it!

**Comment by martyvona** [comment]
ok well let me know if you want me to review it

**Comment by cartermak** [comment]
By all means, have at it. Let me resolve these merge conflicts right now.

**Review by Mythicaeda — APPROVED** [review]
We may want to wait to merge until #32 is almost ready.

**Pull request merged**
